/**
 * Type declarations for the virtual module generated by
 * core/integrations/galleryIntegration.ts. See that file for why this exists.
 */
declare module 'virtual:scms/galleries' {
  type ImageModule = { default: { src: string; width: number; height: number; format?: string } };
  type CaptionsModule = { default: Record<string, string> } | Record<string, string>;

  export const pagesImages: Record<string, ImageModule>;
  export const contentImages: Record<string, ImageModule>;
  export const sharedImages: Record<string, ImageModule>;
  export const pagesCaptions: Record<string, CaptionsModule>;
  export const contentCaptions: Record<string, CaptionsModule>;
  export const sharedCaptions: Record<string, CaptionsModule>;
}
